# This is a basic workflow to help you get started with Actions

name: API Spec Diff

on:
  pull_request:
    types: [opened, reopend, synchronize]

jobs:
  generate-api-spec-diff: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3
          
      # 쿼리파이 레포에 적용시 아래 step 시도.
      # - name: Checkout repository
      #   uses: actions/checkout@v3
      #   with:
      #     token: ${{ secrets.DEV_CHEQUER_GITHUB_TOKEN }}
      #     submodules: true
      #     lfs: true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Generate base branch API spec
        run: |
          echo ${{ github.base_ref }}
          git fetch origin ${{ github.base_ref }}
          git checkout ${{ github.base_ref }}
          ./gradlew generateOpenApiDocs --stacktrace
          mkdir -p api-specs
          find . -name "openapi.json" -exec cp {} api-specs/base-openapi.json \;
          echo "Base branch API spec content:"
          cat api-specs/base-openapi.json || echo "File not found"

      - name: Generate compare branch API spec
        run: |
          echo ${{ github.head_ref }}
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          ./gradlew generateOpenApiDocs --stacktrace
          find . -name "openapi.json" -exec cp {} api-specs/compare-openapi.json \;
          echo "Compare branch API spec content:"
          cat api-specs/compare-openapi.json || echo "File not found"

      - name: Running OpenAPI Spec diff action
        uses: oasdiff/oasdiff-action/changelog@main
        with:
          base: api-specs/base-openapi.json
          revision: api-specs/compare-openapi.json

      - name: Upload API specs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-specs
          path: api-specs/
