# This is a basic workflow to help you get started with Actions

name: Generate and Push OpenAPI Docs

on:
  push:
    branches:
      - 'feature/**'
      - 'release/**'
      - 'develop'

jobs:
  generate-api-spec-diff: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Generate OpenAPI docs
        run: |
          echo ${{ github.head_ref }}
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          ./gradlew generateOpenApiDocs

      - name: Get branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get current date and time
        id: datetime
        run: echo "DATETIME=$(date +'%Y%m%d_%H%M')" >> $GITHUB_OUTPUT

      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: 'MorrisHong/open-api-specs'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: 'specs'
          ref: 'main'
        env:
          ACTIONS_STEP_DEBUG: true

      - name: Copy generated docs to target repo
        run: |
          mkdir -p specs/$BRANCH_NAME
          cp ./openapi.json specs/$BRANCH_NAME/openapi_${{ steps.datetime.outputs.DATETIME }}.json
          cd specs
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update OpenAPI docs for $BRANCH_NAME on ${{ steps.datetime.outputs.DATETIME }}"
          git push
